#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Xam.Droid.SimpleCrop.Demo.Resource", IsApplication=true)]

namespace Xam.Droid.SimpleCrop.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010011
			public const int scv_animation_duration = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int scv_animation_enabled = 2130771984;
			
			// aapt resource value: 0x7f010002
			public const int scv_background_color = 2130771970;
			
			// aapt resource value: 0x7f01000e
			public const int scv_crop_enabled = 2130771982;
			
			// aapt resource value: 0x7f010001
			public const int scv_crop_mode = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int scv_frame_color = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public const int scv_frame_stroke_weight = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int scv_guide_color = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int scv_guide_show_mode = 2130771975;
			
			// aapt resource value: 0x7f01000d
			public const int scv_guide_stroke_weight = 2130771981;
			
			// aapt resource value: 0x7f010005
			public const int scv_handle_color = 2130771973;
			
			// aapt resource value: 0x7f010012
			public const int scv_handle_shadow_enabled = 2130771986;
			
			// aapt resource value: 0x7f010008
			public const int scv_handle_show_mode = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int scv_handle_size = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int scv_img_src = 2130771968;
			
			// aapt resource value: 0x7f01000f
			public const int scv_initial_frame_scale = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int scv_min_frame_size = 2130771979;
			
			// aapt resource value: 0x7f010003
			public const int scv_overlay_color = 2130771971;
			
			// aapt resource value: 0x7f01000a
			public const int scv_touch_padding = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int colorButtonNormal = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int divider = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int overlay = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int textColorPrimary = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int textColorPrimaryInverse = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int windowBackground = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060002
			public const int button_height = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int text_size_m = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int text_size_s = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int original = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080015
			public const int button16_9 = 2131230741;
			
			// aapt resource value: 0x7f080011
			public const int button1_1 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int button3_4 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int button4_3 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int button9_16 = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int buttonCircle = 2131230744;
			
			// aapt resource value: 0x7f080016
			public const int buttonCustom = 2131230742;
			
			// aapt resource value: 0x7f08001c
			public const int buttonDone = 2131230748;
			
			// aapt resource value: 0x7f080010
			public const int buttonFitImage = 2131230736;
			
			// aapt resource value: 0x7f080017
			public const int buttonFree = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int buttonRotateLeft = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int buttonRotateRight = 2131230747;
			
			// aapt resource value: 0x7f080019
			public const int buttonShowCircleButCropAsSquare = 2131230745;
			
			// aapt resource value: 0x7f080000
			public const int circle = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int circle_square = 2131230721;
			
			// aapt resource value: 0x7f08000d
			public const int cropImageView = 2131230733;
			
			// aapt resource value: 0x7f080002
			public const int custom = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int fit_image = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int free = 2131230724;
			
			// aapt resource value: 0x7f08001d
			public const int layout_root = 2131230749;
			
			// aapt resource value: 0x7f08000a
			public const int not_show = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int ratio_16_9 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int ratio_3_4 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int ratio_4_3 = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int ratio_9_16 = 2131230728;
			
			// aapt resource value: 0x7f08001e
			public const int result_image = 2131230750;
			
			// aapt resource value: 0x7f08000b
			public const int show_always = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int show_on_touch = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int square = 2131230729;
			
			// aapt resource value: 0x7f08000e
			public const int tab_bar = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int tab_layout = 2131230735;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Result_Activity = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] scv_CropImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 17
			public const int scv_CropImageView_scv_animation_duration = 17;
			
			// aapt resource value: 16
			public const int scv_CropImageView_scv_animation_enabled = 16;
			
			// aapt resource value: 2
			public const int scv_CropImageView_scv_background_color = 2;
			
			// aapt resource value: 14
			public const int scv_CropImageView_scv_crop_enabled = 14;
			
			// aapt resource value: 1
			public const int scv_CropImageView_scv_crop_mode = 1;
			
			// aapt resource value: 4
			public const int scv_CropImageView_scv_frame_color = 4;
			
			// aapt resource value: 12
			public const int scv_CropImageView_scv_frame_stroke_weight = 12;
			
			// aapt resource value: 6
			public const int scv_CropImageView_scv_guide_color = 6;
			
			// aapt resource value: 7
			public const int scv_CropImageView_scv_guide_show_mode = 7;
			
			// aapt resource value: 13
			public const int scv_CropImageView_scv_guide_stroke_weight = 13;
			
			// aapt resource value: 5
			public const int scv_CropImageView_scv_handle_color = 5;
			
			// aapt resource value: 18
			public const int scv_CropImageView_scv_handle_shadow_enabled = 18;
			
			// aapt resource value: 8
			public const int scv_CropImageView_scv_handle_show_mode = 8;
			
			// aapt resource value: 9
			public const int scv_CropImageView_scv_handle_size = 9;
			
			// aapt resource value: 0
			public const int scv_CropImageView_scv_img_src = 0;
			
			// aapt resource value: 15
			public const int scv_CropImageView_scv_initial_frame_scale = 15;
			
			// aapt resource value: 11
			public const int scv_CropImageView_scv_min_frame_size = 11;
			
			// aapt resource value: 3
			public const int scv_CropImageView_scv_overlay_color = 3;
			
			// aapt resource value: 10
			public const int scv_CropImageView_scv_touch_padding = 10;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
